### ISSUE TITLE
DMP: Development and UAT environment setup

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DMP_roadmap#12]
Based on the current docker and docker-compose work, create proper development/UAT environment for development and user acceptance test. 

Requirements:
- [ ] Bring it in line with Jupiter and Discovery project setup, use simplified/rails default stack as much as possible. 
- [ ] Dev env have local drive mounted. 

For future consideration
- Allow tests with ORCID sandbox, and Canadian Access Federation Sandbox (need shibboleth, and shibboleth-discovery service) in the UAT environment.

**Comment by weiweishi** [comment]
@piyapongch 
Current DMP Roadmap docker is at:
https://github.com/ualbertalib/DMP_roadmap/blob/master/Dockerfile

What needs to be achieved is:
- [ ] A docker-compose file that can be used for a full stack dev environment, and/or deploy to the UAT environment:
https://github.com/ualbertalib/jupiter/blob/master/docker-compose.yml
https://github.com/ualbertalib/jupiter/blob/master/docker-compose.deployment.yml
(Following examples from Jupiter, but might not have to have two separate versions as in Jupiter, or regular dev stack and a deployment version - Jupiter's stack is more complicated) Also, should use mysql instead of postgresql. 
- [ ] Documentation on how this can be used. Also need documentation on how dev env can be set up -  can follow Jupiter's documentation: 
https://github.com/ualbertalib/jupiter/blob/master/README.md#docker

**Comment by weiweishi** [comment]
Could you submit your PR for review @piyapongch
