### ISSUE TITLE
Portage Customization

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DMP_roadmap#19]
As a user of the Portage's DMP Assistant tool, I want all the customization done in DMP Assistant to be ported over to DMP Roadmap so that my experience in the new DMP Roadmap remains the same in the new roadmap application. 

This includes porting over all the customization listed below: 

- [ ] CAF Shibboleth Integration #16 
- [ ] Portage Skin/UI Design #14 
- [ ] Branding customization #15 
- [ ] Customization of Organization template #17 
- [ ] disable funder templates #18 
- [ ] data migration #13 
- [ ] small UI changes #20 #22 #21 
- [ ] French translation review
