### ISSUE TITLE
Docker image for new Roadmap codebase

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DMP_roadmap#2]
This is to create a docker image for new DMP Roadmap code base. It should
- [x] adhere to the requirements outlined here https://github.com/ualbertalib/di_docker_images#requirements--deliverables
- [x] follow the documentation template outlined here: https://github.com/ualbertalib/Developer-Handbook/tree/master/Docker#proposed-readmemd-template-for-di-docker-images
- [x] It needs proper dev/test environment for development
- [x] proper uat environment for CI integration testing (a variation of the production environment)
- [x] Use community image(s) whenever possible (e.g. mysql)
- [x] Setup autobuild in dockerhub
- [x] setup automated testing in dockerhub.

**Comment by weiweishi** [comment]
could you please update this ticket please @astrilet, with proper documentation, and link to the docker repo.

**Comment by alexstrilets** [comment]
Automated build and testing was done on travis not on dockerhub.

**Comment by alexstrilets** [comment]
There is  PR #6  to address issues above

**Comment by alexstrilets** [comment]
Amended  PR #6  (adding_docker) to satisfy above requirements
