### ISSUE TITLE
SPIKE: Feature comparison between DMP Roadmap/DMPOnline v4

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DMP_roadmap#5]
This is to create a comparison chart between the new/existing features:
Areas need particular attentions are:
- [ ] Export/Share Plan (Scope, process etc)
- [ ] Create plan based different template. 
- [ ] Organization Admin interface
  - [ ] logo upload?
  - [ ] organizational template
  - [ ] organizational guidance
Expected Outcome:
- [ ] a complete list of features that we've customized
- [ ] a summary of comparison for features in Roadmap vs in DMP Assistant
- [ ] List of features that need to be migrated, and create milestones based on these features.
